"""
Tier 1 edge extraction: quantified customer/supplier relationships.

Strategy: entity-first approach.
  1. Build a regex pattern from all known company name aliases.
  2. Scan filing text for percentage mentions (X% of revenue/sales).
  3. For each percentage mention, check a context window for a known company.
  4. Determine edge direction (filer names customer vs. filer names supplier)
     from surrounding context words.

This is far more precise than generic company-name capture regexes because
we only consider companies already in our alias table — no false positives
from random capitalized phrases.
"""
from __future__ import annotations

import re
from typing import Optional

# ── Percentage pattern ─────────────────────────────────────────────────────
# Matches "25%", "approximately 25.3%", "25 percent"
_PCT_PAT = re.compile(
    r'(?:approximately\s+)?(\d{1,3}(?:\.\d{1,2})?)\s*(?:%|percent)\s+'
    r'of\s+(?:our\s+)?(?:consolidated\s+)?(?:net\s+)?(?:total\s+)?'
    r'(?:revenue|sales|net sales|revenues|net revenue)',
    re.IGNORECASE
)

# ── Context direction classifiers ──────────────────────────────────────────
_CUSTOMER_VERBS = re.compile(
    r'\b(?:accounted for|represented|comprised|contributed|generated|'
    r'derived from|attributable to|generated by|from|to)\b',
    re.IGNORECASE
)
_SUPPLIER_VERBS = re.compile(
    r'\b(?:manufactured by|produced by|fabricated by|assembled by|'
    r'supplied by|outsourced to|rely on|depend on|primary supplier|'
    r'sole supplier|contract manufacturer|foundry)\b',
    re.IGNORECASE
)

# Window around a percentage mention to search for a company name
_WINDOW = 250  # characters


def build_company_regex(aliases_reverse: dict[str, str]) -> re.Pattern:
    """
    Build a single alternation regex from all known company name aliases.
    Sorted longest-first to prefer more specific matches.
    """
    names = sorted(aliases_reverse.keys(), key=len, reverse=True)
    # Escape and join. Use word boundaries to avoid partial matches.
    escaped = [re.escape(n) for n in names if len(n) >= 3]
    pattern = r'\b(?:' + '|'.join(escaped) + r')\b'
    return re.compile(pattern, re.IGNORECASE)


def extract_tier1_candidates(
    text: str,
    company_re: Optional[re.Pattern] = None,
) -> list[dict]:
    """
    Scan filing text for quantified supply chain relationships.

    Args:
        text:       filing text (Item 1A + Item 1 concatenated)
        company_re: pre-built regex from build_company_regex(); if None,
                    falls back to a generic capitalized-name heuristic.

    Returns list of dicts:
        company_name: str           canonical alias that matched
        pct:          float         revenue share (0–100)
        direction:    str           "names_customer" | "names_supplier"
        snippet:      str           surrounding context (for debugging)
    """
    results: list[dict] = []
    seen: set = set()

    for m in _PCT_PAT.finditer(text):
        pct = float(m.group(1))
        if not (1.0 <= pct <= 99.0):
            continue

        # Context window around this percentage mention
        ctx_start = max(0, m.start() - _WINDOW)
        ctx_end   = min(len(text), m.end() + _WINDOW)
        ctx       = text[ctx_start:ctx_end]

        if company_re is None:
            continue  # without the resolver regex, skip (called from unit tests)

        # Find known company names in the window
        for cm in company_re.finditer(ctx):
            raw_name = cm.group(0)
            # Determine direction from context
            before_pct = ctx[:ctx.find(m.group(0)[:10]) + len(m.group(0)[:10])]
            is_customer = bool(_CUSTOMER_VERBS.search(ctx))
            is_supplier = bool(_SUPPLIER_VERBS.search(ctx))
            direction = "names_supplier" if is_supplier and not is_customer else "names_customer"

            key = (raw_name.lower(), round(pct))
            if key in seen:
                continue
            seen.add(key)

            snippet = ctx[:200].replace('\n', ' ')
            results.append({
                "company_name": raw_name,
                "pct":          pct,
                "direction":    direction,
                "snippet":      snippet,
            })

    # Deduplicate by (company, pct) — keep first occurrence
    return results


# ── Fallback: generic pattern for when no resolver is available ────────────
# Used for ad-hoc debugging / unit tests without loading the full universe.

_GENERIC_CUSTOMER_PATTERNS = [
    re.compile(
        r'([A-Z][A-Za-z0-9 ,\.\-&]{2,50}?(?:Inc\.?|Corp\.?|Ltd\.?|Co\.?|LLC|N\.V\.?|plc)?)'
        r'(?:\s+\w+){0,3}\s+(?:accounted for|represented)\s+'
        r'(?:approximately\s+)?(\d{1,3}(?:\.\d+)?)\s*%\s+'
        r'of\s+(?:our\s+)?(?:net\s+)?(?:total\s+)?(?:revenue|sales)',
        re.IGNORECASE
    ),
]


def extract_tier1_generic(text: str) -> list[dict]:
    """Generic fallback extractor (less precise, no entity awareness)."""
    results, seen = [], set()
    for pat in _GENERIC_CUSTOMER_PATTERNS:
        for m in pat.finditer(text):
            g = m.groups()
            if len(g) < 2:
                continue
            try:
                # Figure out which group is name vs pct
                pct_match = re.search(r'\d+(?:\.\d+)?', g[1])
                name = g[0].strip().strip(",.:;")
                pct = float(pct_match.group()) if pct_match else 0.0
            except (ValueError, AttributeError, IndexError):
                continue
            if not name or not (1.0 <= pct <= 99.0):
                continue
            key = (name.lower()[:20], round(pct))
            if key in seen:
                continue
            seen.add(key)
            results.append({
                "company_name": name,
                "pct":          pct,
                "direction":    "names_customer",
                "snippet":      m.group(0)[:120],
            })
    return results
